# Generated by Django 5.1.3 on 2024-11-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('meals', 'Meals'), ('sweets_and_desserts', 'Sweets and Desserts'), ('snacks', 'Snacks')], default='meals', max_length=20),
        ),
    ]
