# Generated by Django 5.1.3 on 2024-12-03 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Meals', 'Meals'), ('Sweets and Desserts', 'Sweets and Desserts'), ('Snacks', 'Snacks')], default='Meals', max_length=20),
        ),
    ]
